### ISSUE TITLE
[Common] 대회 제출을 위한 코드 정리

### ISSUE THREAD

**Issue by yumdari** [Embedded-Cartel/AWS_DeepRacer#35]

**Comment by SangsO** [comment]
https://github.com/Embedded-Cartel/AWS_DeepRacer/pull/37

Update 완료. 추후 AA쪽 전체 코드 정리 완료 시, Calc 및 모델학습 관련 코드와 동일하게 다른곳도  linux standard coding style 주석 적용 예정.
